CREATE TABLE IF NOT EXISTS payslips (
  id                        INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  store_id                  INT UNSIGNED NOT NULL,
  owner_id                  INT UNSIGNED NOT NULL,
  employee_id               INT UNSIGNED NOT NULL COMMENT 'store_members.id 참조',
  payroll_result_id         INT UNSIGNED NULL DEFAULT NULL,
  period_start              DATE         NOT NULL,
  period_end                DATE         NOT NULL,
  payment_date              DATE         NULL DEFAULT NULL,
  version                   SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  status                    ENUM('DRAFT','CONFIRMED','ISSUED','CORRECTED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
  pay_period_type           ENUM('MONTHLY','WEEKLY','CUSTOM') NOT NULL DEFAULT 'MONTHLY',
  period_label              VARCHAR(100) NOT NULL DEFAULT '',
  gross_pay                 DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_deductions          DECIMAL(12,2) NOT NULL DEFAULT 0,
  net_pay                   DECIMAL(12,2) NOT NULL DEFAULT 0,
  snapshot_json             LONGTEXT     NOT NULL,
  issued_at                 DATETIME     NULL DEFAULT NULL,
  issued_by                 INT UNSIGNED NULL DEFAULT NULL,
  corrected_from_payslip_id INT UNSIGNED NULL DEFAULT NULL,
  correction_reason         TEXT         NULL DEFAULT NULL,
  cancelled_at              DATETIME     NULL DEFAULT NULL,
  cancelled_by              INT UNSIGNED NULL DEFAULT NULL,
  cancellation_reason       TEXT         NULL DEFAULT NULL,
  created_at                DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at                DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_store_employee  (store_id, employee_id),
  INDEX idx_owner           (owner_id),
  INDEX idx_period          (period_start, period_end),
  INDEX idx_status          (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
